// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://todncctpwogbpptjfnxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvZG5jY3Rwd29nYnBwdGpmbnh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDc0ODgsImV4cCI6MjA3MzQyMzQ4OH0.e5gtAXhq_RspOMrfeUFqqGier6gOkcBsw31fSg0mfT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});